name: communication_repository
description: Dart package which manages the socket communication with the server.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  web_socket_channel: ^2.0.0
  equatable: ^2.0.0
