name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.1.0"

dependencies:
  meta: ^1.1.8
  http: ^0.13.0
  equatable: ^2.0.0
  uuid: ^3.0.1
